### ISSUE TITLE
Toaster floats and text-size is too small on mobile

### ISSUE THREAD

**Issue by devonash** [devonash/dsn1676-term-project#1]
I tried putting in a media query to target elements in mobile but, once I put in top, width, height etc., the images on the desktop version got extremely large and images went off the page. 

I was wondering how I could get the toaster to move down, without disrupting other content on the site. As well as enlarge the text a little so that it's more readable on mobile screen sizes.

@thomasjbradley

/*@media only screen and (min-width: 25em) {

```
.fulltoaster {
    top: 300px;
}

.down {
    top: 450px;
    width: 100%;
}
```

}*/

**Comment by thomasjbradley** [comment]
That media query above is targeted at medium screens. Is it the one that's cascading to desktop screens?

**Comment by devonash** [comment]
If I changed the media query to 10em, would that be targeting smaller screens?

**Comment by thomasjbradley** [comment]
Yes, but mobile-sized screens are always targeted outside media queries.

**Comment by devonash** [comment]
Ok, I think that makes more sense. And then I'd target the larger screen sizes using media queries...I'm still wondering why it seems fine when I make the browser size small, but on actual phones, the toaster floats in the middle of the screen.
![screen shot 2015-02-10 at 1 41 01 pm](https://cloud.githubusercontent.com/assets/6373210/6134005/13ce4362-b12c-11e4-8797-ee50bacc306f.png)

**Comment by thomasjbradley** [comment]
Yes, media queries are for larger screens.

Do you have the viewport tag?

**Comment by devonash** [comment]
![screen shot 2015-02-10 at 1 57 32 pm](https://cloud.githubusercontent.com/assets/6373210/6134095/c9c5cd16-b12c-11e4-8c5d-ea67eb21f3ed.png)

Yes

**Comment by thomasjbradley** [comment]
What about the HTML viewport tag?

**Comment by devonash** [comment]
Woops! I forgot that, just put it in now. Now the toaster is below the viewable content on mobile.
