### ISSUE TITLE
Svgs in a pile

### ISSUE THREAD

**Issue by devonash** [devonash/dsn1676-term-project#2]
I tried your idea out with the new svg's! But they all sit on top of each other. Is there a way to make them stack below the billboard?

I used position absolute and a z-index on all of them, and I was thinking that might be the issue.

![screen shot 2015-03-20 at 11 51 19 am](https://cloud.githubusercontent.com/assets/6373210/6755162/81852ba8-cef7-11e4-8f48-515334c3eb9f.png)

@thomasjbradley

**Comment by thomasjbradley** [comment]
I think that 1 out of each group shouldn't be absolute; the one that should be at the back.
So for the pan and egg, the pan shouldn't be absolute.

**Comment by devonash** [comment]
I tried making the image behind relative and those svg's went below the billboard but, the others stayed at the top?

![screen shot 2015-03-20 at 12 06 15 pm](https://cloud.githubusercontent.com/assets/6373210/6755469/c866e01e-cef9-11e4-8221-2d9ef6ca8d9c.png)
![screen shot 2015-03-20 at 12 06 23 pm](https://cloud.githubusercontent.com/assets/6373210/6755474/cb42ca64-cef9-11e4-9d7c-a8f49dc8d849.png)
![screen shot 2015-03-20 at 12 06 42 pm](https://cloud.githubusercontent.com/assets/6373210/6755476/cdcacd72-cef9-11e4-99a5-31981f59e37c.png)

**Comment by thomasjbradley** [comment]
Try making each of the `div` tags they are in relative.
